---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "genai-arcade.fullname" . }}-redis
  labels:
    {{- include "genai-arcade.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  selector:
    {{- include "genai-arcade.selectorLabelsRedis" . | nindent 4 }}
  type: {{ .Values.redis.service.type }}
  ports:
    - name: redis
      port: {{ .Values.redis.service.port }}
      protocol: TCP
      targetPort: redis
